// <auto-generated />
using System;
using FikirHavuzu.Repository.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FikirHavuzu.Repository.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ürün"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hizmet"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Süreç"
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Evaluation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EvaluatedByUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EvaluationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("bit");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedByUserId");

                    b.HasIndex("IdeaId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Idea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TargetedBenefit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("UserId");

                    b.ToTable("Ideas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1095),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 1",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1112),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 2",
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1113),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 3",
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1114),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 4",
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1115),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 5",
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1116),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 6",
                            UserId = 1
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1116),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 7",
                            UserId = 1
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1117),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 8",
                            UserId = 1
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1118),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 9",
                            UserId = 1
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 3,
                            CreatedAt = new DateTime(2026, 7, 30, 20, 23, 32, 280, DateTimeKind.Local).AddTicks(1119),
                            Description = "Bu mimariye geçiş yapmak daha iyi olur",
                            TargetedBenefit = "Mimari iyileştirmesi",
                            Title = "ASP.NET CORE MİMARİSİ 10",
                            UserId = 1
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.IdeaDocument", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdeaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IdeaId");

                    b.ToTable("IdeaDocuments");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Fikirleri görüntüleme yetkisi.",
                            Name = "Idea.View"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Fikir oluşturma yetkisi.",
                            Name = "Idea.Create"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fikirleri karara bağlama, açıklama yazma ve puanlama yetkisi.",
                            Name = "Idea.Evaluate"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Kullanıcı ekleme, güncelleme, pasife alma ve listeleme yetkisi.",
                            Name = "User.Manage"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Kullanıcılara yetki atama ve kaldırma yetkisi.",
                            Name = "Permission.Manage"
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.PermissionDependency", b =>
                {
                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("RequiredPermissionId")
                        .HasColumnType("int");

                    b.HasKey("PermissionId", "RequiredPermissionId");

                    b.HasIndex("RequiredPermissionId");

                    b.ToTable("PermissionDependency");

                    b.HasData(
                        new
                        {
                            PermissionId = 2,
                            RequiredPermissionId = 1
                        },
                        new
                        {
                            PermissionId = 3,
                            RequiredPermissionId = 2
                        },
                        new
                        {
                            PermissionId = 3,
                            RequiredPermissionId = 1
                        },
                        new
                        {
                            PermissionId = 5,
                            RequiredPermissionId = 4
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdentityNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@fikirhavuzu.com",
                            FirstName = "Sistem",
                            IdentityNumber = "11111111111",
                            IsActive = true,
                            LastName = "Yöneticisi",
                            PasswordHash = "$2a$11$oRdgtBQSThMN2hx/.jGh0ezPKyRo2mY.tHPkwbO68mI.GpGijiiYO",
                            PhoneNumber = "05555555555",
                            RegistrationNumber = "0001"
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.UserPermission", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.HasKey("UserId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("UserPermissions");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PermissionId = 1,
                            Id = 0
                        },
                        new
                        {
                            UserId = 1,
                            PermissionId = 2,
                            Id = 0
                        },
                        new
                        {
                            UserId = 1,
                            PermissionId = 3,
                            Id = 0
                        },
                        new
                        {
                            UserId = 1,
                            PermissionId = 4,
                            Id = 0
                        },
                        new
                        {
                            UserId = 1,
                            PermissionId = 5,
                            Id = 0
                        });
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Evaluation", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.User", "EvaluatedByUser")
                        .WithMany("Evaluations")
                        .HasForeignKey("EvaluatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.Idea", "Idea")
                        .WithMany("Evaluations")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EvaluatedByUser");

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Idea", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Category", "Category")
                        .WithMany("Ideas")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.User", "User")
                        .WithMany("Ideas")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.IdeaDocument", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Idea", "Idea")
                        .WithMany("Documents")
                        .HasForeignKey("IdeaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Idea");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.PermissionDependency", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Permission", "Permission")
                        .WithMany("RequiredPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.Permission", "RequiredPermission")
                        .WithMany("DependentPermissions")
                        .HasForeignKey("RequiredPermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("RequiredPermission");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.UserPermission", b =>
                {
                    b.HasOne("FikirHavuzu.Entity.Entities.Permission", "Permission")
                        .WithMany("UserPermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FikirHavuzu.Entity.Entities.User", "User")
                        .WithMany("UserPermissions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Category", b =>
                {
                    b.Navigation("Ideas");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Idea", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Evaluations");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.Permission", b =>
                {
                    b.Navigation("DependentPermissions");

                    b.Navigation("RequiredPermissions");

                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FikirHavuzu.Entity.Entities.User", b =>
                {
                    b.Navigation("Evaluations");

                    b.Navigation("Ideas");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
